repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: /tests/
        # --strict
        args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --implicit-reexport,
          --explicit-package-bases,
        ]
        additional_dependencies: [
          "types-attrs",
          "types-requests"
        ]