repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8