name: Test Runner

on:
  push:
    branches:
      - '**'

jobs:

  test:

    name: Execute tests
    runs-on: ubuntu-latest
    
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install -r requirements.txt
          pytest