name: Test Runner

on:
  push:
    branches:
      - master
      - dev

jobs:

  test:

    name: Execute tests
    runs-on: ubuntu-latest
    
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install .
          pytest --mypy stac_validator
          pytest -v
      - name: Run pre-commit
        run: |
          pre-commit install
	  pre-commit autoupdate
	  pre-commit run --all-files
