name: Test Runner

on:
  push:
    branches:
      - master
      - dev

jobs:

  test:

    name: Execute tests
    runs-on: ubuntu-latest
    
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install --editable .["test"]
          pytest --mypy
      - name: Run pre-commit
        run: make code-check